fix: #4206
appirio-tech/connect-app pull request #4245
Opened 2021-01-06 10:13 UTC by yoution

@maxceem please reivew #4206

2021-01-06 12:37 UTC, maxceem requested changes
@yoution thanks for fast fix. I've noticed a few issues.

1. Styles has changed for the text fields. We have to use the same styles as before:

    ![image](https://user-images.githubusercontent.com/146016/103768360-099c8300-502b-11eb-9b8f-e71e72ffd8ba.png)
    
2. Skills list is not shown, it should be shown. Probably have to pass some other value for `skillsCategories` maybe `undefined` or `null`. Our aim is to show all skills, not only one category.

    ![image](https://user-images.githubusercontent.com/146016/103768410-1de08000-502b-11eb-952a-178b02afd54b.png)
    
3. If I add 3 items, and after remove the second item, then in dropdowns I would see the data from the 3rd, items instead of the 2nd item. See demo video https://monosnap.com/file/eWPhOjBU3CNRX091n5ehcYuVXJoqZN

    This issue usually happens because of using `key={jobIndex}`. Instead of this when creating default values for new row, add some new field, like `key = _.uuid('job_key_')` which would be unique, and use it for `key` instead of `key={jobIndex}`.
 
 I could continue reviewing after these 2 issues are fixed.

2021-01-06 12:37 UTC, maxceem commented on src/projects/detail/components/SpecQuestions.jsx
> +      })
@yoution we don't use options for this component, so this can be removed.

2021-01-06 15:26 UTC, yoution commented
@maxceem  
![image](https://user-images.githubusercontent.com/3863914/103785489-3629bc80-5076-11eb-8013-71d07eaf138c.png)
1. the api between  dev and my local , maybe not the same api, 
2. 
![image](https://user-images.githubusercontent.com/3863914/103785727-86088380-5076-11eb-82a2-a67acd548273.png)
there is no entry for the job page

2021-01-06 16:43 UTC, maxceem commented
![image](https://user-images.githubusercontent.com/146016/103795655-ebe11500-504e-11eb-9ee6-c4903cd0fe90.png)

@yoution this is correct in `tass-jobs-2` branch we use a new endpoint for getting skills without categories.

![image](https://user-images.githubusercontent.com/146016/103795720-fe5b4e80-504e-11eb-9890-651d1827061a.png)

Yeah, we hide it. But you can still use a direct link https://connect.topcoder-dev.com/new-project/taas-jobs

2021-01-06 20:49 UTC, maxceem commented
@yoution regarding showing skills. It was not your issue, I've fixed loading skills in the existent code. Please, pull the latest changes from `appirio-tech:feature/taas-jobs-2` I've used the fix there.

2021-01-07 00:32 UTC, yoution commented
@maxceem please review again

2021-01-07 00:35 UTC, yoution commented
sorry,I forget to change the fix message, I just use the previous message, next time I will pay attention to

2021-01-07 10:39 UTC, maxceem approved these changes
Great @yoution. Everything works good. Merging for testing by QA team.

2021-01-07 10:39 UTC, merged