fix: add easymde #4298
appirio-tech/connect-app pull request #4302
Opened 2021-02-18 08:38 UTC by yoution

2021-02-18 08:39 UTC, yoution commented
@maxceem please review

2021-02-18 09:44 UTC, maxceem requested changes
@yoution generally looks good, but it has a few issues for me:

1. If we have an empty field we show a validation error that is correct. When type one character I expect that the validation error is gone, but it doesn't. And after removing it, the validation error is gone, but it shouldn't. For example, check how title field works and how the description with editor works. It should work the same like title, see demo video https://monosnap.com/file/j1aSlQNabfysgrebw1W42qwL7rwzRy

2. If I type a lot inside the text editor and scrollbar appears, then I can also scroll editor buttons and bottom summary information. But I should only scroll what is inside editor. See demo video https://monosnap.com/file/NqVLbDBXgFY875RB3pHt02BR6TkUsn. And check how it's done in Work Manager for example 

     ![image](https://user-images.githubusercontent.com/146016/108334984-235ce880-71db-11eb-8643-263675197b2c.png)

3. We already use a package to convert Makrdown to HTML https://www.npmjs.com/package/remarkable. Can we reuse it instead of introducing a new package `marked`.  We even have a method which we maybe can reuse [markdownToHTML](https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/markdownToState.js#L215)

4. If we click "Preview Mode" then text would almost have no styles:

    ![image](https://user-images.githubusercontent.com/146016/108337786-2c9b8480-71de-11eb-9760-1890164aa070.png)
    
    Can we have some basic styles for the features that we use: headings, bold/italic, ordered/unordered lists, blockquote, code? Similar to what we have in Work Manager:
    
    ![image](https://user-images.githubusercontent.com/146016/108337979-6b313f00-71de-11eb-8920-3e13c3bdcdb6.png)

Example code:
```
# h1 Heading
## h2 Heading
### h3 Heading
#### h4 Heading
##### h5 Heading
###### h6 Heading

## Emphasis

**This is bold text**

__This is bold text__

*This is italic text*

_This is italic text_

~~Strikethrough~~


## Blockquotes


> Blockquotes can also be nested...
>> ...by using additional greater-than signs right next to each other...
> > > ...or with spaces between arrows.


## Lists

Unordered

+ Create a list by starting a line with `+`, `-`, or `*`
+ Sub-lists are made by indenting 2 spaces:
  - Marker character change forces new list start:
    * Ac tristique libero volutpat at
    + Facilisis in pretium nisl aliquet
    - Nulla volutpat aliquam velit
+ Very easy!

Ordered

1. Lorem ipsum dolor sit amet
2. Consectetur adipiscing elit
3. Integer molestie lorem at massa


1. You can use sequential numbers...
1. ...or keep all the numbers as `1.`

Start numbering with offset:

57. foo
1. bar


## Code

Inline `code`

Indented code

    // Some comments
    line 1 of code
    line 2 of code
    line 3 of code
```


Also, there are few comments for the code below.

2021-02-18 09:44 UTC, maxceem commented on src/components/MarkdownText/MarkdownText.jsx
> +    return (<div className={cn(className, styles.editor, { [styles.isPrivate]: isPrivate })}>
I'm not sure what does`isPrivate` do?

2021-02-18 09:44 UTC, maxceem commented on src/components/MarkdownText/MarkdownText.jsx
> +    this.updateDescriptionThrottled = _.throttle(this.updateDescription.bind(this), 10000) // 10s
Because of this `onChange` would be called only once per 10 seconds. This seems like not a good default behavior. When we reuse this component other logic might want to know the fresh value immediately.

2021-02-18 16:35 UTC, maxceem requested changes
1. You've implemented the `readOnly` mode which is nice to have. But if I enable it (set `readOnly = true`) then there are is an error in the console and the component doesn't work. It can be fixed by `this.refs.textarea.innerHTML = value ? markdownToHTML(value) : ''` and then readonly mode works, but styles looks broken:
   - height should be automatic or with a scrollbar
   - content should not go out
   - content should have the style as when preview

   ![image](https://user-images.githubusercontent.com/146016/108387646-743e0280-7216-11eb-8a54-712617199910.png)
 
 
@yoution I wonder why did you add `throttle` initially? Does typing work slowly for you without `throttle`? Or what was the reason? maybe I'm missing something?

2021-02-18 16:35 UTC, maxceem commented on src/components/MarkdownText/MarkdownText.jsx
> +    // this.updateDescriptionThrottled = _.throttle(this.updateDescription.bind(this), 10000) // 10s
Can we remove this now and rename `updateDescriptionThrottled` to `updateDescription`?

2021-02-18 16:35 UTC, maxceem commented on src/components/MarkdownText/MarkdownText.jsx
> +      })
Do we still need this logic after we don't use `throttle`? Or can it be removed together with `this.setState({ isChanged: true })`?

2021-02-18 16:35 UTC, maxceem commented on src/components/MarkdownText/MarkdownText.jsx
> +      this.ref.current.innerHTML = value ? markdownToHTML(value) : ''
This doesn't work. I guess it should be `this.refs.textarea.innerHTML = value ? markdownToHTML(value) : ''`

2021-02-19 00:59 UTC, yoution commented on src/components/MarkdownText/MarkdownText.jsx
> +    // this.updateDescriptionThrottled = _.throttle(this.updateDescription.bind(this), 10000) // 10s
I don't know why I add the `throttled`, I copy some logic from the * workmanager* project

2021-02-19 12:00 UTC, maxceem approved these changes
All is perfect now. Thank you @yoution for the quick turn arounds.

2021-02-19 12:00 UTC, merged